"""image icon

Revision ID: 10be8d03476f
Revises: 6d94200a5a17
Create Date: 2025-01-09 21:27:27.994749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '10be8d03476f'
down_revision = '6d94200a5a17'
branch_labels = None
depends_on = None


def upgrade():
    # Удаляем внешний ключ
    op.drop_constraint('samples_imageId_fkey', 'samples', type_='foreignkey')

    # Удаляем таблицу
    op.drop_table('images')

    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=128), nullable=True))
        batch_op.drop_column('imageId')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageId', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('samples_imageId_fkey', 'images', ['imageId'], ['id'])
        batch_op.drop_column('image')

    op.create_table('images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='images_pkey')
    )
    # ### end Alembic commands ###
