"""Add relationships

Revision ID: 29a52d24c878
Revises: f9cc1c6eb6af
Create Date: 2024-12-09 17:18:35.420049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a52d24c878'
down_revision = 'f9cc1c6eb6af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=1024), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sampleUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=128), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('sampleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sampleId'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('second_name', sa.String(length=128), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('second_name')
        batch_op.drop_column('first_name')

    op.drop_table('sampleUser')
    op.drop_table('samples')
    # ### end Alembic commands ###
