"""small fix

Revision ID: 5017b7a25387
Revises: 29a52d24c878
Create Date: 2024-12-09 18:55:06.325868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5017b7a25387'
down_revision = '29a52d24c878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=1048576),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.String(length=1048576),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=False)

    # ### end Alembic commands ###
