"""sample image new

Revision ID: 6d94200a5a17
Revises: 8874eee271a3
Create Date: 2024-12-19 22:06:21.685348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6d94200a5a17'
down_revision = '8874eee271a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imageId', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'images', ['imageId'], ['id'])
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('imageId')

    op.drop_table('images')
    # ### end Alembic commands ###
