"""sample upgrade

Revision ID: 756ab808dfb0
Revises: 96fd4e437ed4
Create Date: 2024-12-11 13:38:38.538961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756ab808dfb0'
down_revision = '96fd4e437ed4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('date_create', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.drop_column('date_update')
        batch_op.drop_column('date_create')
        batch_op.drop_column('state')

    # ### end Alembic commands ###
