"""restart base

Revision ID: 96fd4e437ed4
Revises: 
Create Date: 2024-12-10 13:18:25.545263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96fd4e437ed4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samples',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=True),
    sa.Column('second_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sampleUser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.String(length=128), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('sampleId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sampleId'], ['samples.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sampleUser')
    op.drop_table('users')
    op.drop_table('samples')
    # ### end Alembic commands ###
