"""small fix

Revision ID: 99e1dfaea938
Revises: 5017b7a25387
Create Date: 2024-12-09 19:43:45.857238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e1dfaea938'
down_revision = '5017b7a25387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.VARCHAR(length=1048576),
               type_=sa.LargeBinary(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samples', schema=None) as batch_op:
        batch_op.alter_column('data',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=1048576),
               existing_nullable=False)

    # ### end Alembic commands ###
